baseURL = "https://lenon.dev/"
languageCode = "en-us"
title = "lenon.dev"
theme = "hugo-bearblog"
author = "Lenon Oliveira"
copyright = "Copyright © 2021, Lenon Oliveira."

[params]
  hideMadeWithLine = true

[markup.highlight]
  tabWidth = 2
